/* MYSQL */
export const JAMBONES_MYSQL_HOST = process.env.JAMBONES_MYSQL_HOST;
export const JAMBONES_MYSQL_USER = process.env.JAMBONES_MYSQL_USER;
export const JAMBONES_MYSQL_PORT = process.env.JAMBONES_MYSQL_PORT;
export const JAMBONES_MYSQL_PASSWORD = process.env.JAMBONES_MYSQL_PASSWORD;
export const JAMBONES_MYSQL_DATABASE = process.env.JAMBONES_MYSQL_DATABASE;
export const JAMBONES_MYSQL_CONNECTION_LIMIT = process.env.JAMBONES_MYSQL_CONNECTION_LIMIT;

/* MYSQL Write Connection */
export const JAMBONES_MYSQL_WRITE_HOST = process.env.JAMBONES_MYSQL_WRITE_HOST;
export const JAMBONES_MYSQL_WRITE_USER = process.env.JAMBONES_MYSQL_WRITE_USER;
export const JAMBONES_MYSQL_WRITE_PORT = process.env.JAMBONES_MYSQL_WRITE_PORT;
export const JAMBONES_MYSQL_WRITE_PASSWORD = process.env.JAMBONES_MYSQL_WRITE_PASSWORD;
export const JAMBONES_MYSQL_WRITE_DATABASE = process.env.JAMBONES_MYSQL_WRITE_DATABASE;

/* Redis */
export const JAMBONES_REDIS_SENTINELS = process.env.JAMBONES_REDIS_SENTINELS;
export const JAMBONES_REDIS_SENTINEL_MASTER_NAME = process.env.JAMBONES_REDIS_SENTINEL_MASTER_NAME;
export const JAMBONES_REDIS_HOST = process.env.JAMBONES_REDIS_HOST;
export const JAMBONES_REDIS_PORT = process.env.JAMBONES_REDIS_PORT;

/* DRACHTIO */
export const DRACHTIO_HOST = process.env.DRACHTIO_HOST;
export const DRACHTIO_PORT = process.env.DRACHTIO_PORT;
export const DRACHTIO_SECRET = process.env.DRACHTIO_SECRET;

/* Application */
export const JAMBONES_TIME_SERIES_HOST = process.env.JAMBONES_TIME_SERIES_HOST;
export const JAMBONES_LOGLEVEL = process.env.JAMBONES_LOGLEVEL;
export const NODE_ENV = process.env.NODE_ENV;
export const SBC_PUBLIC_ADDRESS_KEEP_ALIVE_IN_MILISECOND = process.env.SBC_PUBLIC_ADDRESS_KEEP_ALIVE_IN_MILISECOND;
export const JAMBONES_HOSTING = process.env.JAMBONES_HOSTING;
export const EXPIRES_INTERVAL = process.env.EXPIRES_INTERVAL;
export const CHECK_EXPIRES_INTERVAL = process.env.CHECK_EXPIRES_INTERVAL;
export const JAMBONES_CLUSTER_ID = process.env.JAMBONES_CLUSTER_ID;
export const JAMBONES_REGBOT_CONTACT_USE_IP = process.env.JAMBONES_REGBOT_CONTACT_USE_IP;
export const JAMBONES_REGBOT_MIN_EXPIRES_INTERVAL = process.env.JAMBONES_REGBOT_MIN_EXPIRES_INTERVAL;
export const JAMBONES_REGBOT_DEFAULT_EXPIRES_INTERVAL = process.env.JAMBONES_REGBOT_DEFAULT_EXPIRES_INTERVAL;
export const JAMBONES_REGBOT_BATCH_SLEEP_MS = process.env.JAMBONES_REGBOT_BATCH_SLEEP_MS || '250';
export const JAMBONES_REGBOT_BATCH_SIZE = process.env.JAMBONES_REGBOT_BATCH_SIZE || '10';
export const OPTIONS_RESPONSE_REMOVE = process.env.OPTIONS_RESPONSE_REMOVE?.split(',').map(Number) || [];
export const REGISTER_RESPONSE_REMOVE = process.env.REGISTER_RESPONSE_REMOVE?.split(',').map(Number) || [];
export const JAMBONES_REGBOT_USER_AGENT = process.env.JAMBONES_REGBOT_USER_AGENT;
export const JAMBONES_REGBOT_FAILURE_RETRY_INTERVAL = process.env.JAMBONES_REGBOT_FAILURE_RETRY_INTERVAL;
